name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping the App
        run: |
          curl -I --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://resumebuilderpy-puwkqmoskvdljojvxfgj2t.streamlit.app/

      - name: Update Heartbeat File
        run: |
          date > heartbeat.txt
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add heartbeat.txt
          git commit -m "Automated heartbeat update" || echo "No changes to commit"
          git push
